[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200